verbose: true
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
instrumentation:
    excludes: ['**/*test.*.js']
    extensions:
         - .js
reporting:
    print: summary
    reports:
        - html
    dir: ./coverage/node/cover
